# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2



    # 下载文件
    - name: 【Cache】 ROM
      id: cache-primes
      uses: actions/cache@master
      env:
        cache-name: mi9
      with:
        path: ./rom
        key: ${{ runner.os }}-${{ env.cache-name }}

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: |
        cd ./rom
        wget http://bigota.d.miui.com/20.4.27/miui_CEPHEUS_20.4.27_2b15191b0e_10.0.zip
    
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        chmod +x extract.sh
        sh extract.sh
        ls -lna
        echo Add other actions to build,
        echo test, and deploy your project.
